version: '3'
services:
  mysql:
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=application
      - MYSQL_PASSWORD=application
      - MYSQL_DATABASE=ama
    volumes:
      - ./data/mysql/:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d     # 초기 SQL 자동 실행

  redis:
    image: redis:7.0.11
    ports:
      - "6379:6379"

networks:
  default:
    driver: bridge