spring:
  datasource:
    url: jdbc:mysql://askmyapi-db-1.c1me6i8iixoe.ap-northeast-2.rds.amazonaws.com:3306/ama?useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: askmyapi2025!
  data:
    redis:
      host: localhost
      port: 6379