spring:
  datasource:
    url: jdbc:mysql://localhost:3307/ama?useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: application
    password: "application"
  data:
    redis:
      host: localhost
      port: 6379